server:
  port: 9000

management:
  server:
    port: 9001
    address: 127.0.0.1

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.xxAMIDOxx.xxSTACKSxx, com.xxAMIDOxx.xxSTACKSxx.api.v1.menu

azure:
  cosmosdb:
    uri: http://your-cosmosDb-uri
    key: your-cosmosDb-key
    secondaryKey: your-cosmosDb-secondary-key
    database: your-cosmosDb-dbName
    populateQueryMetrics: false
