server:
  port: 9000

management:
  endpoints:
    web:
      base-path: /

springdoc:
  api-docs:
    path: /swagger/index.html
  packagesToScan: com.xxAMIDOxx.xxSTACKSxx, com.xxAMIDOxx.xxSTACKSxx.api.v1.menu

azure:
  cosmosdb:
    uri: http://your-cosmosDb-uri
    key: your-cosmosDb-key
    secondaryKey: your-cosmosDb-secondary-key
    database: your-cosmosDb-dbName
    populateQueryMetrics: false
