spring:
  application:
    name:

server:
  port: 9000

management:
  endpoints:
    web:
      base-path: /

springdoc:
  api-docs:
    path: /swagger/oas.json
  swagger-ui:
    path: /swagger/index.html
  packagesToScan: com.xxAMIDOxx.xxSTACKSxx, com.xxAMIDOxx.xxSTACKSxx.api.v1.menu

azure:
  cosmosdb:
    uri: https://amidostacksmenucdauksdev.documents.azure.com:443/
    database: Stacks
    key: YgdCWbMDmLOEmfrmAJMKOugN2uK3r4VIfEfITguUfW7MFM0tfvagus8OGqnCAn49G9QIm7HcpsTW36o2cwaH1w==
    secondaryKey:
    populateQueryMetrics: false
  application-insights:
    instrumentation-key: 741cf94a-b6d3-4321-b32d-40eb9ed4f840
    enabled: true
  keyvault:
    enabled: true
    uri: https://amido-stacks-tmp.vault.azure.net/
    client-id: 54bc588e-207e-47dd-9f1a-d90888d35ad7
    client-key: put-your-azure-client-key-here
    tenant-id:
