spring:
  application:
    name:

server:
  port: 9000

management:
  endpoints:
    web:
      base-path: /

springdoc:
  api-docs:
    path: /swagger/index.html
  packagesToScan: com.xxAMIDOxx.xxSTACKSxx, com.xxAMIDOxx.xxSTACKSxx.api.v1.menu

azure:
  cosmosdb:
    uri: https://amidostacksmenucdauksdev.documents.azure.com:443/
    key: <cosmos_key>
    secondaryKey: YYY
    database: Stacks
    populateQueryMetrics: false
  application-insights:
    instrumentation-key: <appinsights_key>
    enabled: true
