spring:
  application:
    name: xxSTACKSxx-api
  data:
    rest:
      detection-strategy: annotated

server:
  port: 9000

# The basepath, passed in as `API_BASEPATH` by Kubernetes.
api:
  basepath: '/'

management:
  endpoints:
    web:
      base-path: /

springdoc:
  api-docs:
    path: ${api.basepath}/v3/api-docs
  swagger-ui:
    configUrl: ${api.basepath}/v3/api-docs/swagger-config
    path: /swagger/index.html
  packagesToScan: com.xxAMIDOxx.xxSTACKSxx.menu.api.v1

azure:
  cosmosdb:
    uri: https://amido-stacks-dev-eun-java-api.documents.azure.com:443/
    database: Stacks
    key: xxxxxx
  application-insights:
    instrumentation-key: xxxxxx
    enabled: true
  keyvault:
    enabled: false
    uri: https://amido-stacks-tmp.vault.azure.net/
    client-id: xxxxxx
    client-key: xxxxxx
    tenant-id: xxxxxx
  servicebus:
    connectionString: xxxxxx
    topicName: menu-updates
    subscriptionName: Subscription1
    enabled: false
